"""initial schema

Revision ID: f2be8d67d02b
Revises: 
Create Date: 2026-07-23 16:26:36.891275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2be8d67d02b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('correlation_id', sa.Uuid(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_customer_ref', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_external_customer_ref'), 'customers', ['external_customer_ref'], unique=True)
    op.create_table('merchants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_name', sa.String(length=200), nullable=False),
    sa.Column('merchant_domain', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('reputation_score', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('blacklisted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_merchant_domain'), 'merchants', ['merchant_domain'], unique=True)
    op.create_table('model_registry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('model_type', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('artifact_path', sa.String(length=300), nullable=False),
    sa.Column('feature_schema_version', sa.String(length=40), nullable=False),
    sa.Column('deployment_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('external_account_id', sa.String(length=120), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('masked_iban', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_customer_id'), 'accounts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_accounts_external_account_id'), 'accounts', ['external_account_id'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=200), nullable=False),
    sa.Column('device_type', sa.String(length=40), nullable=False),
    sa.Column('network_carrier_type', sa.String(length=40), nullable=False),
    sa.Column('ip_address_type', sa.String(length=40), nullable=False),
    sa.Column('trusted', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_customer_id'), 'devices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_devices_device_fingerprint'), 'devices', ['device_fingerprint'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_device_id'), 'transactions', ['device_id'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_id'), 'transactions', ['merchant_id'], unique=False)
    op.create_table('fraud_assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('raw_probability', sa.Float(), nullable=False),
    sa.Column('calibrated_probability', sa.Float(), nullable=False),
    sa.Column('decision_threshold', sa.Float(), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('risk_category', sa.String(length=30), nullable=False),
    sa.Column('ui_risk_level', sa.String(length=10), nullable=False),
    sa.Column('recommended_action', sa.String(length=40), nullable=False),
    sa.Column('ui_recommendation', sa.String(length=10), nullable=False),
    sa.Column('processing_time_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_assessments_created_at'), 'fraud_assessments', ['created_at'], unique=False)
    op.create_index(op.f('ix_fraud_assessments_risk_category'), 'fraud_assessments', ['risk_category'], unique=False)
    op.create_index(op.f('ix_fraud_assessments_transaction_id'), 'fraud_assessments', ['transaction_id'], unique=True)
    op.create_table('assessment_explanations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('feature_name', sa.String(length=80), nullable=False),
    sa.Column('feature_display_name', sa.String(length=160), nullable=False),
    sa.Column('feature_value', sa.String(length=200), nullable=False),
    sa.Column('shap_value', sa.Float(), nullable=False),
    sa.Column('impact_direction', sa.String(length=12), nullable=False),
    sa.Column('importance_rank', sa.Integer(), nullable=False),
    sa.Column('explanation_en', sa.String(length=300), nullable=False),
    sa.Column('explanation_ar', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['fraud_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_explanations_assessment_id'), 'assessment_explanations', ['assessment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_explanations_assessment_id'), table_name='assessment_explanations')
    op.drop_table('assessment_explanations')
    op.drop_index(op.f('ix_fraud_assessments_transaction_id'), table_name='fraud_assessments')
    op.drop_index(op.f('ix_fraud_assessments_risk_category'), table_name='fraud_assessments')
    op.drop_index(op.f('ix_fraud_assessments_created_at'), table_name='fraud_assessments')
    op.drop_table('fraud_assessments')
    op.drop_index(op.f('ix_transactions_merchant_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_device_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_devices_device_fingerprint'), table_name='devices')
    op.drop_index(op.f('ix_devices_customer_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_accounts_external_account_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_customer_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('model_registry')
    op.drop_index(op.f('ix_merchants_merchant_domain'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_customers_external_customer_ref'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
